cluster.name: "elasticsearch_cluster"
network.host: 0.0.0.0

http.port: 9210
transport.port: 9310
xpack.security.enabled: false

node.name: slave
cluster.initial_master_nodes: 
  - master
discovery.seed_hosts: 
  - master:9300