http.port: 9350 #elasticsearch Node 사용할 포트번호
network.host: 0.0.0.0
node.name: master #elasticsearch Node 이름
node.roles: master,ingest #elasticsearch Node role 정책 (master,data,ml,등)
path.repo: "/usr/share/elasticsearch/data" #클러스터 백업 시 생성하게 되는 스냅샷 repository의 path 값
cluster.name: elasticsearch-cluster #클러스터 이름
discovery.seed_hosts: data1,data2 #cluster를 구성할 node를 node 이름으로 찾는 설정
cluster.initial_master_nodes: master # 최초 cluster 구성시에 마스터 노드로 선정될 노드 후보를 명시
bootstrap.memory_lock: true #swap memory 사용에 대해 제한 설정
xpack.security.enabled: true #xpack을 통한 보안설정 여부 
xpack.license.self_generated.type: trial #xpack license의 종류 설정          
xpack.security.http.ssl.enabled: true # ssl을 통해 외부에서 노드 접속시 https 통신으로 암호화 설정 여부
xpack.security.http.ssl.key: /usr/share/elasticsearch/config/certificates/master/master.key #https 통신 시 사용하게 될 Key의 path 값
xpack.security.http.ssl.certificate_authorities: /usr/share/elasticsearch/config/certificates/ca/ca.crt #https 통신 시 사용하게 될 ca인증서 파일의 Path 값
xpack.security.http.ssl.certificate: /usr/share/elasticsearch/config/certificates/master/master.crt #https 통신 사 사용하게 될 crt 인증서 파일 path 값
xpack.security.transport.ssl.enabled: true #TLS 통신 설정 여부 
xpack.security.transport.ssl.verification_mode: certificate #TLS 통신 시 설정 옵션 (certificate, none 등)
xpack.security.transport.ssl.certificate_authorities: /usr/share/elasticsearch/config/certificates/ca/ca.crt #TLS 통신 시 사용하게 될 CA 인증서 파일의 path 값
xpack.security.transport.ssl.certificate: /usr/share/elasticsearch/config/certificates/master/master.crt #TLS 통신 시 사용하게 될 crt 인증서 파일 path 값
xpack.security.transport.ssl.key: /usr/share/elasticsearch/config/certificates/master/master.key ##TLS 통신 시 사용하게 될 key 인증서 파일 path 값
