version: '3.8'
services:
  # elasticsearch master node container 생성  
  data2:
    #사용되는 elasticsearch image 
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    #container
    container_name: data2
    ulimits:
      memlock:
        soft: -1
        hard: -1    
    ports:
      - 9230:9230
      - 9330:9330
    volumes: 
      - ./config/data_jvm.options:/usr/share/elasticsearch/config/jvm.options
      - ./config/data2_conf.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - data2_data:/usr/share/elasticsearch/data
      - data2_logs:/usr/share/elasticsearch/logs

volumes:
  data2_data:
  data2_logs:
