version: "3.8"
services:
  make-directory:
    image: ubuntu:latest

    volumes:
      - type: bind
        source: ./
        target: /usr/share/
    command: sh -c "mkdir -p /usr/share/master/data /usr/share/master/logs"

  elasticsearch_master_node:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    container_name: es_master_node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    env_file:
      - ../../env/master.env
    ports:
      - 9350:9200
      - 9450:9300
    volumes:
      - ../../config/prod/master/jvm.options:/usr/share/elasticsearch/config/jvm.options
      - ./master/data:/usr/share/elasticsearch/data
      - ./master/logs:/usr/share/elasticsearch/logs

    depends_on:
      - make-directory
