version: "3.8"
services:
  make-directory-other:
    image: ubuntu:latest
    volumes:
      - type: bind
        source: ./
        target: /usr/share/
    command: sh -c "mkdir -p /usr/share/other/data /usr/share/other/logs"

  elasticsearch_other_node:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    container_name: es_other_node
    command: sh -c "./bin/elasticsearch --enrollment-token aaeyJ2ZXIiOiI4LjMuMyIsImFkciI6WyIxNzIuMjcuMC4zOjkyMDAiXSwiZmdyIjoiZGI2YjZmZjBhMTg2ZTNjNTdiOGFmZjRhYmI5ZjEyM2NlOTQ3MWRkMTk3OTYwZTkzN2UwZjhmZTBkNjhlZTM1MCIsImtleSI6ImNnc1dOb2NCRlpNallIV2xQQkxTOkpHVFlGXzhaVDhlODZHRkFHLURzRVEifQ=="
    env_file:
      - ../../env/other.env
    ulimits:
      memlock:
        soft: -1
        hard: -1

    ports:
      - 8350:9200
      - 8450:9300
    volumes:
      - ../../config/prod/master/jvm.options:/usr/share/elasticsearch/config/jvm.options
      - ./master/data:/usr/share/elasticsearch/data
      - ./master/logs:/usr/share/elasticsearch/logs

    depends_on:
      - make-directory-other
