version: '3.8'
services:
  # elasticsearch master node container 생성  
  master:
    #사용되는 elasticsearch image 
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    #container
    container_name: master
    ulimits:
      memlock:
        soft: -1
        hard: -1    
    ports:
      - 9200:9200
      - 9300:9300
    #volume path 설정  
    volumes: 
      - ./config/jvm.options:/usr/share/elasticsearch/config/jvm.options
      - ./config/master_conf.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - master_data:/usr/share/elasticsearch/data
      - master_logs:/usr/share/elasticsearch/logs

volumes:
  master_data:
  master_logs:

