version: '3.8'
services:
  # elasticsearch master node container 생성  
  slave:
    #사용되는 elasticsearch image 
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    #container
    container_name: slave
    ulimits:
      memlock:
        soft: -1
        hard: -1    
    ports:
      - 9210:9210
      - 9310:9310
    volumes: 
      - ./config/jvm.options:/usr/share/elasticsearch/config/jvm.options
      - ./config/slave_conf.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - slave_data:/usr/share/elasticsearch/data
      - slave_logs:/usr/share/elasticsearch/logs

volumes:
  slave_data:
  slave_logs:
