version: '3.8'
services:


  # 필요 디렉토리 생성 - 해당노드는 생성 후 command 작업이 끝나면 down 상태로 변경 됨
  make-directory:
    image: ubuntu:latest
    entrypoint: /bin/bash
    volumes:
      - type: bind
        source: ./
        target: /usr/share/
    user: "0:0"
    command: 
      - -c
      - |
        mkdir -p /usr/share/slave_data /usr/share/slave_logs
        chmod -R 777 /usr/share/


  # elasticsearch master node container 생성  
  slave:
    #사용되는 elasticsearch image 
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    #container
    container_name: slave
    ulimits:
      memlock:
        soft: -1
        hard: -1    
    ports:
      - 9210:9210
      - 9310:9310
    volumes: 
      - $SLAVE_JVM_PATH:/usr/share/elasticsearch/config/jvm.options
      - $SLAVE_CONF_PATH:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./slave_data:/usr/share/elasticsearch/data
      - ./slave_logs:/usr/share/elasticsearch/logs

    # #container 내부 통신을 위한 브릿지 네트워크 생성   
    # network_mode: "host"  
