# Default Kibana configuration for docker target
server.host: "0.0.0.0"
server.shutdownTimeout: "20s"
elasticsearch.hosts: ["https://master:9350"]


elasticsearch.username: kibana_system
elasticsearch.password: timegate1!

server.ssl.enabled: true
server.ssl.key: /usr/share/kibana/config/certificates/kibana/kibana.key
server.ssl.certificate: /usr/share/kibana/config/certificates/kibana/kibana.crt

elasticsearch.ssl.certificateAuthorities: /usr/share/kibana/config/certificates/ca/ca.crt
monitoring.ui.container.elasticsearch.enabled: true



      # SERVERNAME: localhost
      # # 연결하고자 하는 elasticsearch master node url 주소 입력 (설정하지 않아도 연결에 문제는 없다고 나오나 확인필요)
      # ELASTICSEARCH_URL: https://esmaster01:9350
      # # 연결하고자 하는 elasticsearch master node 주소
      # ELASTICSEARCH_HOSTS: https://esmaster01:9350
      # # elasticsearch 로 접근할때 사용할 auth 계정 정보
      # ELASTICSEARCH_USERNAME: kibana_system
      # # 비밀번호의 경우 보안설정 프로세스에 따라 진행하여 해당 값을 채워주어야 함
      # ELASTICSEARCH_PASSWORD: CxBnlesPKuSIIaBFQYpq
      # # kibana에서 사용하게 될 ca 인증서 path 값
      # ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES: $CERTS_DIR/ca/ca.crt
      # # ssl 인증서를 통한 https 통신 설정 여부
      # SERVER_SSL_ENABLED: "true"
      # # https 통신 시 사용하게 될 key path 값
      # SERVER_SSL_KEY: $CERTS_DIR/kib01/kib01.key
      # # https 통신 시 사용하게 될 crt 파일 path 값
      # SERVER_SSL_CERTIFICATE: $CERTS_DIR/kib01/kib01.crt