version: '3.8'
services:
  elasticsearch_sigle_node:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    container_name: es_single_node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9350:9200
      - 9450:9300
    volumes:
      #- ../../config/single:/usr/share/elasticsearch/config
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./config/jvm.options:/usr/share/elasticsearch/config/jvm.options
      - data:/usr/share/elasticsearch/data
      - logs:/usr/share/elasticsearch/logs

    depends_on:
      - make-directory
volumes:
  data:
  logs: