version: '3.8'
services:


  # 필요 디렉토리 생성 - 해당노드는 생성 후 command 작업이 끝나면 down 상태로 변경 됨
  make-directory:
    image: ubuntu:latest
    entrypoint: /bin/bash
    volumes:
      - type: bind
        source: ./
        target: /usr/share/
    user: "0:0"
    command: 
      - -c
      - |
        mkdir -p /usr/share/data_data /usr/share/data_logs
        chmod -R 777 /usr/share/



  # elasticsearch master node container 생성  
  data:
    #사용되는 elasticsearch image 
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    #container
    container_name: data
    ulimits:
      memlock:
        soft: -1
        hard: -1

    environment:
      - http.port=9360
      - cluster.name=elastic-stack
      - node.roles:[data]
      - "ES_JAVA_OPTS=-Xmx2g -Xms2g"
      - ENROLLMENT_TOKEN=$ENROLLMENT_TOKEN       
    #volume path 설정  
    volumes: 
      # master(dedicate node) log를 확인하기위한 bind 마운트
      - ./data_logs:/usr/share/elasticsearch/logs
      - ./data_data:/usr/share/elasticsearch/data
      # docker volume을 통해 config 정보 유지를 위해 named 마운트
      - data_config1:/usr/share/elasticsearch/config
      - data_plugin1:/usr/share/elasticsearch/plugins

    #container 내부 통신을 위한 브릿지 네트워크 생성   
    network_mode: "host"  

volumes:
  data_config1:
    driver: local
  data_plugin1:
    driver: local
